module.exports = {
  'aal'          : 'Attribution Assurance License (AAL)',
  'afl-3.0'      : 'Academic Free License 3.0 (AFL-3.0)',
  'apl-1.0'      : 'Adaptive Public License (APL-1.0)',
  'agpl-3.0'     : 'Affero GNU Public License 3.0 (AGPL-3.0)',
  'apache-2.0'   : 'Apache License, Verison 2.0 (Apache-2.0)',
  'apsl-2.0'     : 'Apple Public Source License (APSL-2.0)',
  'artistic-2.0' : 'Artistic License (Artistic-2.0)',
  'bsd-2-clause' : 'BSD 2-Clause "Simplified" or "FreeBSD" License (BSD-2-Clause)',
  'bsd-3-clause' : 'BSD 3-Clause "New" or "Revised" License (BSD-3-Clause)',
  'bsl-1.0'      : 'Boost Software License (BSL-1.0)',
  'catosl-1.1'   : 'Computer Associates Trusted Open Source License 1.1 (CATOSL-1.1)',
  'cddl-1.0'     : 'Computer Associates Trusted Open Source License 1.0 (CDDL-1.0)',
  'cecill-2.1'   : 'CeCILL License (CECILL-2.1)',
  'cpal-1.0'     : 'Common Public Attribution License 1.0 (CPAL-1.0)',
  'cua-opl-1.0'  : 'CUA Office Public License Version 1.0 (CUA-OPL-1.0)',
  'ecl-2.0'      : 'Educational Community License, Version 2.0 (ECL-2.0)',
  'entessa'      : 'Entessa Public License Version 1.0 (Entessa)',
  'eudatagrid'   : 'EU Datagrid Software License (EUDatagrid)',
  'gpl-3.0'      : 'GNU General Public License 3.0 (GPL-3.0)',
  'isc'          : 'ISC License (ISC)',
  'mit'          : 'The MIT License (MIT)',
  'mpl-2.0'      : 'Mozilla Public License Version 2.0 (MPL-2.0)',
  'ms-pl'        : 'Microsoft Public License (MS-PL)',
  'w3c'          : 'The W3C SOFTWARE NOTICE AND LICENSE (W3C)',
  'zlib-libpng'  : 'The zlib/libpng License (Zlib)'
};
